language: shell

addons:
  homebrew:
    packages:
    update: false
  apt:
    update: true
    packages:
    - build-essential

stages:
  - name: "No dependencies" # Doesn't depend on anything apart from upstream packages
    if: type != cron
  - name: "Has first level dependencies" # Depends on a package in the "no dependencies" group
    if: type != cron
  - name: "Main label upload" # Puts Anaconda packages to the main label
    if: type = push AND branch = master
  - name: "Cleanup" # Job for removing old Anaconda labels
    if: type = cron

jobs:
  include:
  # No dependencies
    - stage: "No dependencies"
      os: linux
      dist: xenial
      env:
      - PACKAGE=dtc
    - stage: "No dependencies"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=dtc
    - stage: "No dependencies"
      os: linux
      dist: xenial
      env:
      - PACKAGE=wishbone-tool
    - stage: "No dependencies"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=wishbone-tool
    - stage: "No dependencies"
      os: windows
      env:
      - PACKAGE=wishbone-tool
    - stage: "No dependencies"
      os: linux
      dist: xenial
      env:
      - PACKAGE=sigrok-cli
    - stage: "No dependencies"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=sigrok-cli
    - stage: "No dependencies"
      os: linux
      dist: xenial
      env:
      - PACKAGE=renode
    - stage: "No dependencies"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=renode
    - stage: "No dependencies"
      os: windows
      env:
      - PACKAGE=renode
    - stage: "No dependencies"
      os: linux
      env:
      - PACKAGE=capnproto
    - stage: "No dependencies"
      os: linux
      env:
      - PACKAGE=zachjs-sv2v

    - stage: "Has first level dependencies"
      os: linux
      env:
      - PACKAGE=capnproto-java

  # Move packages from the current label to main
    - stage: "Main label upload"
      os: linux
      dist: xenial
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/master-package.sh

  # Remove old labels
    - stage: "Cleanup"
      os: linux
      dist: xenial
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/cleanup-anaconda.sh

  fast_finish: true

  allow_failures:
    - stage: "No dependencies"
      os: linux
      dist: xenial
      env:
      - PACKAGE=renode
    - stage: "No dependencies"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=renode
    - stage: "No dependencies"
      os: windows
      env:
      - PACKAGE=renode

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - bash $TRAVIS_BUILD_DIR/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
