language: shell

addons:
  homebrew:
    packages:
    update: false
stages:
  - "Miscellaneous"

jobs:
  include:
  # Miscellaneous
    - stage: "Miscellaneous"
      os: linux
      dist: xenial
      env:
      - PACKAGE=dtc
    - stage: "Miscellaneous"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=dtc
    - stage: "Miscellaneous"
      os: linux
      dist: xenial
      env:
      - PACKAGE=wishbone-tool
    - stage: "Miscellaneous"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=wishbone-tool
    - stage: "Miscellaneous"
      os: windows
      env:
      - PACKAGE=wishbone-tool
    - stage: "Miscellaneous"
      os: linux
      dist: xenial
      env:
      - PACKAGE=sigrok-cli
    - stage: "Miscellaneous"
      os: linux
      dist: xenial
      env:
      - PACKAGE=renode
    - stage: "Miscellaneous"
      os: osx
      osx_image: xcode8.3
      env:
      - PACKAGE=renode
    - stage: "Miscellaneous"
      os: windows
      env:
      - PACKAGE=renode
  fast_finish: true

before_install:
 - source $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/fixup-git.sh
 - bash $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/download_sdk.sh
 - source $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/common.sh

install:
 - ./litex-conda-ci/.travis/install.sh

script:
 - bash $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/script.sh

after_failure:
 - bash $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/after_failure.sh

after_success:
 - bash $TRAVIS_BUILD_DIR/litex-conda-ci/.travis/after_success.sh

cache:
  directories:
   - $HOME/.conda/pkgs
