name: build-packages
on: [push, pull_request]
jobs:
  packages:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {package: "dtc", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
          - {package: "dtc", os: "macos-latest", os-name: "osx", shell: "bash"}
          - {package: "wishbone-tool", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
          - {package: "wishbone-tool", os: "macos-latest", os-name: "osx", shell: "bash"}
          - {package: "wishbone-tool", os: "windows-latest", os-name: "windows", shell: "bash"}
          - {package: "sigrok-cli", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
          - {package: "sigrok-cli", os: "macos-latest", os-name: "osx", shell: "bash"}
          - {package: "renode", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
          - {package: "renode", os: "macos-latest", os-name: "osx", shell: "bash"}
          - {package: "renode", os: "windows-latest", os-name: "windows", shell: "bash"}
          - {package: "capnproto", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
          - {package: "zachjs-sv2v", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
          - {package: "capnproto-java", os: "ubuntu-16.04", os-name: "linux", shell: "bash"}
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    steps:
    - name: Check where's Chocolatey
      if: matrix.os-name == 'windows'
      run: where choco
      shell: cmd
    - name: Check where's winpty.exe
      if: matrix.os-name == 'windows'
      run: where winpty
      shell: cmd
    - name: Check where's msys64
      if: matrix.os-name == 'windows'
      run: ls C:\msys64
      shell: powershell
    - name: Add msys2 to PATH
      if: matrix.os-name == 'windows'
      run: echo "C:\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell
    - name: Checkout workspace
      uses: actions/checkout@v2
    - name: build
      env:
        PACKAGE: ${{ matrix.package }}
        OS_NAME: ${{ matrix.os-name }}
      run: |
        export PATH="$PATH:/c/ProgramData/Chocolatey/bin/"
        export PATH="$PATH:/c/Program Files/Git/usr/bin/"
        echo $PATH
        unset TMP
        unset TEMP
        source .github/scripts/common.sh
        bash .github/scripts/fixup-git.sh
        bash .github/scripts/download_sdk.sh
        source .github/scripts/common.sh
        bash .github/scripts/install.sh
        bash .github/scripts/script.sh
    - name: build2
      env:
        PACKAGE: ${{ matrix.package }}
        OS_NAME: ${{ matrix.os-name }}
      run: |
        echo $PATH
    - name: on_success
      env:
        PACKAGE: ${{ matrix.package }}
      if: success()
      run: |
        source .github/scripts/after_success.sh
    - name: on_failure
      env:
        PACKAGE: ${{ matrix.package }}
      if: failure()
      run: |
        source .github/scripts/after_failure.sh
