name: build-packages
on: [push, pull_request]
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  NUM_OF_JOBS: 13
defaults:
  run:
    shell: bash
jobs:

  #1
  dtc-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "dtc"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: antmicro/litex-conda-ci@test-conda-config-remote

  #2
  dtc-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "dtc"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #3
  wishbone-tool-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #4
  wishbone-tool-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #5
  wishbone-tool-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "wishbone-tool"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #6
  sigrok-cli-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "sigrok-cli"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #7
  sigrok-cli-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sigrok-cli"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #8
  renode-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "renode"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #9
  renode-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "renode"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: brew install coreutils
      - uses: litex-hub/litex-conda-ci@master

  #10
  renode-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "renode"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #11
  capnproto-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "capnproto"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #12
  zachjs-sv2v-linux:
    runs-on: "ubuntu-16.04"
    env:
      PACKAGE: "zachjs-sv2v"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  #13
  capnproto-java-linux:
    runs-on: "ubuntu-16.04"
    needs: "capnproto-linux"
    env:
      PACKAGE: "capnproto-java"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: litex-hub/litex-conda-ci@master

  master-package:
    runs-on: "ubuntu-16.04"
    env:
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: urllib3
      - run: |
          bash .github/scripts/install.sh
          python .github/scripts/wait-for-statuses.py
